name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no Docker Hun
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      -  name: Contruçção de Imagem Docker
         uses: docker/build-push-actions@v6
         with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
           gomesdocker/fina-api:latest
           gomesdocker/fina-api:v${{ github.run_number }}


