name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@<action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
         args: >
          - Dsonar.projectKey=prodesps
         projectBaseDir: ./src 
         scanMetadataReportFile: ./src/.scannerwork/report-task.txt
 

      - name: Autenticar no Docker Hun
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      -  name: Contrução de Imagem Docker
         uses: docker/build-push-action@v6
         with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
           gomesdocker/fina-api:latest
           gomesdocker/fina-api:v${{ github.run_number }}


